name: ecommercial
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:

  auth_repo:
   path: packages/auth_repo

  database_repo:
   path: packages/database_repo 

  flutter:
    sdk: flutter

 
  

  form_inputs:
   path: packages/form_inputs
   
  formz: ^0.4.0  
  firebase_core: ^1.22.0
  firebase_auth: ^3.8.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  cloud_firestore: ^3.4.7
  meta: ^1.8.0
  very_good_analysis: ^3.0.2
  font_awesome_flutter: ^10.1.0
  google_fonts: ^3.0.1
  flow_builder: ^0.0.9
  badges: ^2.0.3
  flutter_native_splash: ^2.2.9
  
  
dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mockito: ^5.3.0




flutter_native_splash:
    color: "#ffffff"
    image: assets/logo1.png
    android: true
    ios: true


flutter:

  
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/assets/imgs/
   


   # - assets/images/sign-in.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
